server:
  port: ${PORT:5216}

spring:
  rabbitmq:
    host: ${RABBIT_URL:localhost}
  application:
    name: time-keeping-microservice
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017/}
      database: time-keeping-db