server:
  port: ${PORT:5213}

spring:
  rabbitmq:
    host: ${RABBIT_URL:localhost}
  application:
    name: customer-microservice
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017/}
      database: customer-db