server:
  port: ${PORT:5214}

spring:
  rabbitmq:
    host: ${RABBIT_URL:localhost}
  application:
    name: employee-microservice
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017/}
      database: employee-db